FIRST_PAGE_URL = "https://bitcointalk.org/index.php?board=238.0"
TABLE_NAME_HOME_PAGE = "topic"
TABLE_NAME_COMMENT_PAGE_PROOF = "comments_proof"
TABLE_NAME_COMMENT_PAGE_PARTICIPATION = "comments_participation"
TABLE_NAME_GOOGLE_SHEETS = "google_sheets"
